### ISSUE TITLE
accepting all code review comments here

### ISSUE THREAD

**Issue by ALPANNA-GH** [ALPANNA-GH/awesome-books#4]

**Comment by maximoortelli** [comment]
### Awesome Books Proyect:

_Hello Alpanna, how are you? I hope that very good. I just saw your work and honestly it's excellent, I have nothing to suggest, you're approved🦾😄_

**Comment by gilberthappi** [comment]
Your project is complete! There is nothing else to say 
Happy coding 
Cheers.

**Comment by smas0900** [comment]
Good job! 👏. just saw Your Code it's Awesome! 💪
